import { createHash } from "node:crypto"
import { mkdir, readFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { describeTool, getToolContract } from "../src/contracts/tool-registry"
import type { JsonValue } from "../src/shared/json"
import { ToolName } from "../src/tools/catalog"

const root = resolve(import.meta.dir, "..")
const generatedDir = resolve(root, "docs", "generated")
const snapshotPath = resolve(generatedDir, "tool-contracts.json")
const referencePath = resolve(generatedDir, "tool-contracts.md")
const compatibilityPath = resolve(generatedDir, "chatgpt-compatibility.md")
const check = process.argv.includes("--check")

const contracts = Object.values(ToolName)
  .sort()
  .map((name) => {
    const contract = getToolContract(name)
    return {
      ...describeTool(name),
      examples: contract.examples,
    }
  })

const contractPayload = stable({ schemaVersion: 1, toolCount: contracts.length, tools: contracts })
const contractJson = `${JSON.stringify(contractPayload, null, 2)}\n`
const fingerprint = createHash("sha256").update(contractJson).digest("hex")
const reference = renderReference(contracts, fingerprint)
const compatibility = renderCompatibility(contracts.length, fingerprint)

await mkdir(generatedDir, { recursive: true })
await writeOrCheck(snapshotPath, contractJson)
await writeOrCheck(referencePath, reference)
await writeOrCheck(compatibilityPath, compatibility)

async function writeOrCheck(path: string, expected: string): Promise<void> {
  if (!check) {
    await Bun.write(path, expected)
    return
  }
  let actual = ""
  try {
    actual = await readFile(path, "utf8")
  } catch {
    throw new Error(`Generated contract artifact is missing: ${path}`)
  }
  if (actual !== expected) {
    throw new Error(
      `Generated contract artifact is stale: ${path}. Run bun run generate:contracts.`,
    )
  }
}

function renderReference(
  entries: ReadonlyArray<ReturnType<typeof describeTool> & { examples: unknown }>,
  hash: string,
): string {
  const rows = entries.map(
    (entry) =>
      `| \`${entry.name}\` | ${entry.risk} | ${entry.mutatesNetSuite ? "yes" : "no"} | ${entry.phaseSupport.join(", ")} |`,
  )
  return `# Generated Tool Contract Reference

This file is generated by \`bun run generate:contracts\`. Do not edit it manually.

- Contract schema version: \`1\`
- Contract fingerprint: \`${hash}\`
- Tool count: \`${entries.length}\`

| Tool | Risk | Mutates NetSuite | Phases |
|---|---|---|---|
${rows.join("\n")}
`
}

function renderCompatibility(toolCount: number, hash: string): string {
  return `# ChatGPT Tool Catalog Compatibility

This file is generated from the current MCP contract registry.

- Contract schema version: \`1\`
- Contract fingerprint: \`${hash}\`
- Tool count: \`${toolCount}\`
- Cache behavior: ChatGPT custom apps cache MCP tool definitions.

After any fingerprint or tool-count change, refresh or recreate the ChatGPT custom app connector before testing. A connector that still reports an older fingerprint or tool count is incompatible with this build even when the HTTP endpoint is reachable.
`
}

function stable(value: unknown): JsonValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value
  }
  if (Array.isArray(value)) {
    return value.map(stable)
  }
  if (typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .filter(([, item]) => item !== undefined)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, item]) => [key, stable(item)]),
    )
  }
  throw new Error(`Unsupported contract value in ${dirname(snapshotPath)}`)
}
